= Query Parser for Apache Impala

This project contains instructions, and some helper libraries to enable the parsing of SQL in Apache Impala's dialect as part of the continuous integration build pipeline. In general, catching common mistakes early on in the development cycle (as opposed to waiting for a deployment) has significant productivity benefits.

== WARNING

CAUTION: This project is still under construction ! Please check back later for updates.

== Building

Before you can utilise/build this library you need to create a local build of https://github.com/apache/impala[Apache Impala]. You need to start with a release version of Impala

=== Getting the Source

You can get the appropriate version of Apache Impala from GitHub:

```
git clone https://github.com/apache/impala.git

git checkout tags/3.4.0

```

=== Building the Source

NOTE: These instructions have been tested with Ubuntu 18.04. You may need to create a VM that has this exact version.

https://cwiki.apache.org/confluence/display/IMPALA/Building+Impala - the Impala Build instructions.

Effectively:

```
export IMPALA_HOME=`pwd`
./bin/bootstrap_development.sh
```

And then after the first build:

```
# Rebuild both backend and frontend
${IMPALA_HOME}/buildall.sh -skiptests -noclean
```

Or even quicker - if you just wish to do the Java:

```
# Incremental builds
source ${IMPALA_HOME}/bin/impala-config.sh
# Optional: Build the Java-side frontend only
make -j$IMPALA_BUILD_THREADS java
```

Publish to the local maven repository:

```

mvn org.apache.maven.plugins:maven-install-plugin:2.5.2:install-file -Dfile./Impala-Build/impala-frontend-uber-4.0.0-SNAPSHOT-jar-with-dependencies.jar

```



